# Generated by Django 6.0.6 on 2026-06-12 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=5)),
                ('division', models.CharField(choices=[('A', 'Div A'), ('B', 'Div B'), ('C', 'Div C'), ('D', 'Div D'), ('ALL', 'All Divisions')], default='ALL', max_length=5)),
                ('update_type', models.CharField(choices=[('homework', 'Homework / Classwork'), ('test', 'Revision Test'), ('notice', 'Important Notice'), ('fee', 'Fee Reminder'), ('circular', 'PDF Circular'), ('event', 'Event / Holiday'), ('material', 'Textbook / Material')], max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General'), ('english', 'English'), ('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('maths', 'Maths'), ('science', 'Science'), ('social', 'Social Science'), ('computer', 'Computer'), ('art', 'Art'), ('pe', 'PE / Sports')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='updates.schoolupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('update', 'user')},
            },
        ),
    ]
