# Generated by Django 6.0.6 on 2026-06-12 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=5)),
                ('division', models.CharField(choices=[('A', 'Div A'), ('B', 'Div B'), ('C', 'Div C'), ('D', 'Div D'), ('ALL', 'All Divisions')], default='ALL', max_length=5)),
                ('subject', models.CharField(choices=[('general', 'General'), ('english', 'English'), ('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('maths', 'Maths'), ('science', 'Science'), ('social', 'Social Science'), ('computer', 'Computer'), ('art', 'Art'), ('pe', 'PE / Sports')], max_length=20)),
                ('class_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, help_text='What was covered in class')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of the notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-class_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notes/%Y/%m/')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notes.classnote')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='NoteHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='notes.classnote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('note', 'user')},
            },
        ),
    ]
